/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const fs = require('fs');
const path = require('path');

// Helper to recursively find markdown files
function getFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  files.forEach((file) => {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getFiles(filePath, fileList);
    } else {
      if (file.endsWith('.md') || file.endsWith('.mdx')) {
        fileList.push(filePath);
      }
    }
  });
  return fileList;
}

// Extract frontmatter tags simply (regex)
function getTagsAndId(content) {
  const tagMatch = content.match(/tags:\s*\n((?:\s*-\s*.*\n?)+)/);
  const idMatch = content.match(/^id:\s*(.*)$/m);

  let tags = [];
  if (tagMatch) {
    tags = tagMatch[1]
      .split('\n')
      .map(line => line.replace(/^\s*-\s*/, '').trim())
      .filter(t => t);
  }

  return { tags, id: idMatch ? idMatch[1].trim() : null };
}

// Generate data
const docsDir = path.join(__dirname, 'docs');
const allFiles = getFiles(docsDir);

const tagCategories = {
  'Aromas': [],
  'Cliente': [],
  'Curso': []
};

// List of all post URLs for random page
const allPostUrls = [];

allFiles.forEach(absolutePath => {
  const relativePath = path.relative(docsDir, absolutePath);
  const content = fs.readFileSync(absolutePath, 'utf8');
  const { tags } = getTagsAndId(content);

  // Create docId for sidebar (remove extension)
  const docId = relativePath.replace(/\.mdx?$/, '');

  // URL path for random page (assuming /docs/ prefix and file structure)
  // Converting backslashes to slashes for URL
  const urlPath = '/docs/' + docId.split(path.sep).join('/');

  // Filter out non-content files if necessary, or just add all
  allPostUrls.push(urlPath);

  // Populate categories
  tags.forEach(tag => {
    // Normalize tag check
    Object.keys(tagCategories).forEach(targetTag => {
      if (tag.toLowerCase() === targetTag.toLowerCase()) {
        tagCategories[targetTag].push({
          type: 'doc',
          id: docId
        });
      }
    });
  });
});

// Write static/all-posts.json
const staticDir = path.join(__dirname, 'static');
if (!fs.existsSync(staticDir)) fs.mkdirSync(staticDir);
fs.writeFileSync(path.join(staticDir, 'all-posts.json'), JSON.stringify(allPostUrls));

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'link',
      label: '🎲 Post Aleatório',
      href: '/random',
    },
    {
      type: 'category',
      label: 'Aromas',
      items: tagCategories['Aromas'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Cliente',
      items: tagCategories['Cliente'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Curso',
      items: tagCategories['Curso'],
      collapsed: true,
    },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
