---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs
  label: Docs
  create: documents
  match: "*.md"
  templates:
  - page
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "*.md"
- type: document
  path: sidebars.json
  label: Sidebar
upload_dir: ''
public_path: https://bebiodicionario-com.s3.sa-east-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: 'uploads/:filename:'
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
